services:
  postgres:
    image: postgres:latest
    container_name: pg-db
    environment:
      POSTGRES_USER: efrem
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pg_dump
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backup:/backup
volumes:
  pgdata: